In [1]:
import numpy as np

# NUMPY

In [2]:
# ndim = know number of dimention


In [5]:
np.random.randint(2,99) # generate random number

40

In [8]:
np.random.randint(2,99, (3,4))# will generate 3(dimention) cols and 4 rows

array([[69, 36, 75, 41],
       [40, 66, 68, 86],
       [62, 78, 16, 80]])

In [9]:
np.random.randint(2,99, (2,3,4))

array([[[61, 78, 92, 70],
        [92, 69, 76, 58],
        [10, 22, 59, 18]],

       [[89, 20, 48, 61],
        [91, 79, 27, 27],
        [79, 12, 71, 55]]])

In [10]:
np.random.rand(2,3) # will generate random float data

array([[0.07085438, 0.1344986 , 0.17837926],
       [0.52677752, 0.25930895, 0.12330695]])

In [12]:
np.random.randn(4,4) # normally distributaed data (average of the data will be close to 0)

array([[-0.99597266, -0.48900436, -0.25104075, -0.48066817],
       [-0.90745734,  0.37335762, -0.21342699, -0.70147172],
       [-0.88740494,  0.76756962,  0.43059555, -0.01084048],
       [ 0.19343638,  0.16946537, -0.29247273,  0.82165285]])

In [13]:
A1 = np.random.randn(4,4)

In [14]:
A1.reshape(8,2) # array can be reshaped by total dim values (4x4 = 16) (8x2=16)

array([[ 1.09418394,  0.19857399],
       [-0.21141686, -1.28984977],
       [-0.01692623, -0.79290079],
       [ 0.81664945, -0.65850726],
       [-0.4787054 ,  0.2975737 ],
       [-0.86726729,  0.55945213],
       [ 1.80455607, -0.64811205],
       [-0.68431034, -0.74153401]])

In [17]:
a5 = np.random.randint(2,90,(6,5))
a5

array([[80, 40, 68, 12, 62],
       [61,  8, 15, 53, 87],
       [46, 29, 46, 52, 61],
       [56,  5,  7, 86, 70],
       [75, 53, 46,  4, 38],
       [35, 24, 84, 75, 17]])

In [16]:
a5[a5>40] 

array([48, 47, 65, 64, 61, 78, 74, 66, 51, 51, 67, 89, 86, 45, 89, 56, 44,
       72, 42, 57, 84, 58])

In [20]:
a5[0,1] = 333 #slicing assignment

In [22]:
a5

array([[ 80, 333,  68,  12,  62],
       [ 61,   8,  15,  53,  87],
       [ 46,  29,  46,  52,  61],
       [ 56,   5,   7,  86,  70],
       [ 75,  53,  46,   4,  38],
       [ 35,  24,  84,  75,  17]])

In [24]:
a6 = np.random.randint(0,3, (3,2))
a6

array([[0, 2],
       [0, 1],
       [2, 0]])

In [28]:
a7 = np.random.randint(0,5,(2,2))
a7

array([[3, 3],
       [1, 2]])

In [26]:
a6*a7 # multiply element to element

array([[0, 6],
       [0, 0],
       [8, 0]])

In [29]:
a6@a7 # matrix multiplication

array([[2, 4],
       [1, 2],
       [6, 6]])

In [30]:
a6 +100 #multiply

array([[100, 102],
       [100, 101],
       [102, 100]])

In [31]:
a6/0

C:\Users\joshi\AppData\Local\Temp\ipykernel_11824\1058679823.py:1: RuntimeWarning: divide by zero encountered in true_divide
  a6/0
C:\Users\joshi\AppData\Local\Temp\ipykernel_11824\1058679823.py:1: RuntimeWarning: invalid value encountered in true_divide
  a6/0


array([[nan, inf],
       [nan, inf],
       [inf, nan]])

In [39]:
a2 = np.zeros((4,4)) # create zero valued array
a2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones((3,3)) # all elements valued 1

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [36]:
np.array([[1,2,3,4]]).T # transpose the data

array([[1],
       [2],
       [3],
       [4]])

In [38]:
a2 + np.array([[1,2,3,4]]).T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [40]:
np.sqrt(a2) # square root

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.log10(a2) # log values

C:\Users\joshi\AppData\Local\Temp\ipykernel_11824\715148170.py:1: RuntimeWarning: divide by zero encountered in log10
  np.log10(a2)


array([[-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf],
       [-inf, -inf, -inf, -inf]])

In [45]:
list(range(0,10, 2))

[0, 2, 4, 6, 8]

In [46]:
np.arange(10) # numpy range 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
np.arange(10,20,3.3) # numpy range 

array([10. , 13.3, 16.6, 19.9])

In [49]:
np.linspace(2,3, num = 10) # range bw 2,3 and num is number of outputs 

array([2.        , 2.11111111, 2.22222222, 2.33333333, 2.44444444,
       2.55555556, 2.66666667, 2.77777778, 2.88888889, 3.        ])

# Data Visulization

# Plotly and Cufflinks

In [1]:
import cufflinks as cf
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
cf.go_offline()

In [3]:
df = pd.DataFrame(np.random.randn(100,3), columns = ['a','b','c'])

In [4]:
df

a         b         c
0   0.453997  0.137265 -1.360588
1   0.090257  1.111920 -0.058885
2   0.240539 -2.164598  0.596586
3  -1.626107  0.318041  0.741938
4   1.356576 -1.793921  0.448439
..       ...       ...       ...
95 -0.939912  2.465639 -0.797909
96 -0.242408  1.147736  0.102707
97  0.176491 -1.202862  0.053006
98  0.128586  0.037608  1.271022
99  0.279909  0.951222  0.130448

[100 rows x 3 columns]

In [5]:
df.iplot()

In [8]:
df1 = pd.DataFrame(np.random.randint(3,100,(100,1)))

In [9]:
df1.iplot()

In [12]:
df.iplot(x = 'a',y = 'b', mode = 'markers')

In [14]:
df2 = sns.load_dataset('titanic')

In [15]:
df2.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [19]:
df2.iplot(x = 'fare', y = 'pclass', mode = 'markers')

In [22]:
df2.iplot(kind = 'bar', x = 'sex', y = 'survived')